#!/bin/bash

# This script configures the system locale.

# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your option)
# any later version. Please take a look at http://www.gnu.org/copyleft/gpl.htm

# Original code from localeconfig, Jean-Philippe Guillemin <jp.guillemin~at~free~dot~fr>
# Modified by: Pierrick Le Brun <akuna~at~free~dot~fr>
# Modified by: George Vlahavas <vlahavas~at~gmail~dot~com>

# Translations only work with utf8 locales
if [ ! `echo $LANG | grep -i utf` ]; then
	LANG=C
fi

# Gettext internationalization
export TEXTDOMAIN="localesetup"
export TEXTDOMAINDIR="/usr/share/locale"
. gettext.sh

# Take a look at "Xdialog" and use it instead of "dialog" in case X is running
if [[ "$DISPLAY" && "$(which Xdialog 2>&1 | grep -v "which: no")" ]]; then
	dialog="Xdialog --wrap --left --screen-center"
else
	dialog="dialog"
fi

# Path to icon
iconpath="/usr/share/salixtools/pixmaps/"

# Path needs to be extended in case you're only half a root :)
export PATH="/usr/sbin:/sbin:${PATH}"

# probe for available locales and generate a menu

currentlocale="$(cat /etc/profile.d/lang.sh \
  | grep -E "^[[:space:]]*export LANG=" \
  | sed -e "s/^[ ]*export LANG=\(.*\)$/\1/")"


list="$(locale -cva \
| grep -A 2 utf8 | sed '/^-/d' \
| sed '
/^locale:.*directory.*/{
s/^locale: \([^ ]*\) *directory.*$/\1/
N
s/^\(.*\) *\n *title . \(.*\)$/"\1" "\2 " \\/'}
)"


locale="$(eval $dialog \
--stdout \
--title \"`eval_gettext 'System language configuration'`\" \
--default-item \"${currentlocale}\" \
--ok-label "`eval_gettext 'OK'`" \
--cancel-label "`eval_gettext 'Exit'`" \
--icon \"$iconpath\" \
--menu \
\"\\n`eval_gettext 'The current locale is $currentlocale.'` \\n\\n\
`eval_gettext 'Please select your preferred system language:'`\" 0 0 11 \
"${list}"
)"

if [ "$locale" ]; then
  sed -i "s/^ *\(export LANG=\).*$/\1$locale/" /etc/profile.d/lang.sh
  /bin/bash /etc/profile.d/lang.sh

fi

# end




