#!/bin/bash

# This script configures the system locale.

# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your option)
# any later version. Please take a look at http://www.gnu.org/copyleft/gpl.htm

# Original code from localeconfig, Jean-Philippe Guillemin <jp.guillemin~at~free~dot~fr>
# Modified by: Pierrick Le Brun <akuna~at~free~dot~fr>
# Modified by: George Vlahavas <vlahavas~at~gmail~dot~com>

# Translations only work with utf8 locales
if [ ! `echo $LANG | grep -i utf` ]; then
	LANG=C
fi

# Gettext internationalization
export TEXTDOMAIN="localesetup"
export TEXTDOMAINDIR="/usr/share/locale"
. gettext.sh

# Path needs to be extended in case you're only half a root :)
export PATH="/usr/sbin:/sbin:${PATH}"

dialog="dialog"

# Just to be sure
unset locale newlocale

# usage screen
usage(){
	echo "`eval_gettext 'USAGE: localesetup [locale]'`"
	echo "`eval_gettext 'EXAMPLE: localesetup en_US'`"
	exit 1
}

if [ $# -gt 1 ]; then
	echo "`eval_gettext 'ERROR: Too many arguments'`"
	usage
fi

if [ ! -z $1 ]; then
	newlocale="`echo $1 | sed 's/UTF-8/utf8/'`"
	if [[ `locale -cva |grep locale | grep utf8 | sed "s/locale: \(.*\) *directory.*/\1/"| grep "^$newlocale\|$newlocale.utf8"` ]]; then
		locale="`echo $newlocale | sed "s/.utf8//"`.utf8"
		echo "`eval_gettext 'Setting locale to $locale'`"
	else
		echo "`eval_gettext 'ERROR: $newlocale is not a valid locale'`"
		usage
	fi
else

# start of interactive section

# find current locale
currentlocale="$(cat /etc/profile.d/lang.sh \
  | grep -E "^[[:space:]]*export LANG=" \
  | sed -e "s/^[ ]*export LANG=\(.*\)$/\1/")"

# probe for available locales
list="$(locale -cva \
| grep -A 2 utf8 | sed '/^-/d' \
| sed '
/^locale:.*directory.*/{
s/^locale: \([^ ]*\) *directory.*$/\1/
N
s/^\(.*\) *\n *title . \(.*\)$/"\1" "\2 " \\/'}
)"

# generate a menu
locale="$(eval $dialog \
--stdout \
--title \"`eval_gettext 'System language configuration'`\" \
--default-item \"${currentlocale}\" \
--ok-label "`eval_gettext 'OK'`" \
--cancel-label "`eval_gettext 'Exit'`" \
--menu \
\"\\n`eval_gettext 'The current locale is $currentlocale.'` \\n\\n\
`eval_gettext 'Please select your preferred system language:'`\" 0 0 11 \
"${list}"
)"

fi

# end of interactive section

# set locale
if [ "$locale" ]; then
  sed -i "s/^ *\(export LANG=\).*$/\1$locale/" /etc/profile.d/lang.sh
  /bin/bash /etc/profile.d/lang.sh
fi

# end

