#!/bin/bash

# This script configures the mirrors that are used in
# /etc/slapt-get/slapt-getrc and /etc/slapt-get/slapt-srcrc

init(){
	# Translations only work with utf8 locales
	if [ ! `echo $LANG | grep -i utf` ]; then
		LANG=C
	fi

	# Gettext internationalization
	export TEXTDOMAIN="reposetup"
	export TEXTDOMAINDIR="/usr/share/locale"
	. gettext.sh
	
	# Path needs to be extended in case you're only half a root :)
	export PATH="/usr/sbin:/sbin:${PATH}"

	# Path to the salixtools shared files
	salixtoolsdir="/usr/share/salixtools/"

	# Paths to the slapt-* configuration files
	SLAPTGETRC="/etc/slapt-get/slapt-getrc"
	SLAPTSRCRC="/etc/slapt-get/slapt-srcrc"

	# Patch to the slapt-* binaries
	SLAPTGET="/usr/sbin/slapt-get"
	SLAPTSRC="/usr/bin/slapt-src"

	# Set to interactive mode by default
	INTERACTIVE=1

	# Set to update repos by default (or ask for update if in
	# interactive mode)
	UPDATE=1
}

checkdefaults(){
	# determine arch
	case "$( uname -m )" in
		i?86) export arch=i486 ;;
		arm*) export arch=arm ;;
		*) export arch=$( uname -m ) ;;
	esac
	
	# slackware arm has a slightly different directory name
	if [ $arch == "arm" ]; then
		slackdir="slackwarearm"
	else
		slackdir="slackware"
	fi	

	# read salix version
	version=$( cat $salixtoolsdir/salix-version )

	CURRENTREPO=""

	# slapt-getrc
	if [ -f $SLAPTGETRC ]; then
		SLAPTGETWORKINGDIR=$( cat $SLAPTGETRC | grep "^WORKINGDIR=" | head -n 1 | sed "s/^WORKINGDIR=\(.*\)/\1/" )
		SLAPTGETEXCLUDE=$( cat $SLAPTGETRC | grep "^EXCLUDE=" | head -n 1 | sed "s/^EXCLUDE=\(.*\)/\1/" )
	else
		SLAPTGETWORKINGDIR="/var/slapt-get"
		if [ $arch == "x86_64" ]; then
			SLAPTGETEXCLUDE="^aaa_elflibs,^aaa_base,^devs,^glibc.*,^kernel-.*,^udev,^rootuser-settings,^zzz-settings.*,-i?86-"
		else
			SLAPTGETEXCLUDE="^aaa_elflibs,^aaa_base,^devs,^glibc.*,^kernel-.*,^udev,^rootuser-settings,^zzz-settings.*,-x86_64-"
		fi
	fi
	
	# keep CUSTOM slapt-get repos in a temporary file
	grep "CUSTOM$" $SLAPTGETRC > /tmp/reposetup.$$

	# slapt-srcrc
	if [ -f $SLAPTSRCRC ]; then
		CURRENTREPO=$( cat $SLAPTSRCRC | grep "^SOURCE=" | grep "slkbuild" | sed "s/^SOURCE=\(.*\)\/slkbuild\/\(.*\)/\1/" )
		SLAPTSRCBUILDDIR=$( cat $SLAPTSRCRC | grep "^BUILDDIR=" | head -n 1 | sed "s/^BUILDDIR=\(.*\)/\1/" )
		SLAPTSRCPKGEXT=$( cat $SLAPTSRCRC | grep "^PKGEXT=" | head -n 1 | sed "s/^PKGEXT=\(.*\)/\1/" )
	else
		SLAPTSRCBUILDDIR="/usr/src/slapt-src"
		SLAPTSRCPKGEXT="txz"
	fi
}

# The interactive section
interactive(){

	list="$( cat $salixtoolsdir/reposetup/repomirrors )"
	
	# Display server selection dialog
	repo="$(eval dialog \
	--stdout \
	--title \"`eval_gettext 'Select repository mirror'`\" \
	--default-item \"$CURRENTREPO\" \
	--ok-label \"`eval_gettext 'Select'`\" \
	--cancel-label \"`eval_gettext 'Cancel'`\" \
	--menu \
	\"\\n`eval_gettext 'Please select your preferred repository mirror. The country code of where the mirror is located is shown on the right. Your selection will be applied to the /etc/slapt-get/slapt-getrc and /etc/slapt-get/slapt-srcrc files:'`\\n\\n`eval_gettext 'WARNING: Any changes you have manually made in the SOURCE lines of those files will be lost!'`\" 20 80 11 $list )"

	# Don't do anything if Cancel or the close button was pressed
	retval=$?
	if [ $retval -eq 1 ] || [ $retval -eq 255 ]; then
		exit 0
	fi
}

updatecache(){
	if [ $INTERACTIVE -eq 1 ]; then
		answer="$(eval dialog \
		--stdout \
		--title \"`eval_gettext 'Update package caches?'`\" \
		--yes-label \"`eval_gettext 'Update'`\" \
		--no-label \"`eval_gettext 'Do not update'`\" \
		--yesno \"`eval_gettext 'Would you like to update the package and SlackBuild caches now?'`\" \
		0 0 )"
		retval=$?
	else
		retval=0
	fi
	if [ $retval -eq 0 ]; then
		$SLAPTGET --update && $SLAPTSRC --update
	fi
}

configslaptget() {
	(
	echo "# Working directory for local storage/cache."
	echo "WORKINGDIR=$SLAPTGETWORKINGDIR"
	echo ""
	echo "# Exclude package names and expressions."
	echo "# To exclude pre and beta packages, add this to the exclude:"
	echo "#   [0-9\_\.\-]{1}pre[0-9\-\.\-]{1}"
	echo "EXCLUDE=$SLAPTGETEXCLUDE"
	echo ""
	echo "# This is a Slackware repository that only holds dependency info. The"
	echo "# actual packages are downloaded from a real Slackware mirror. Read"
	echo "# http://docs.salixos.org/wiki/How_to_create_a_local_slackware_repository_with_dependency_support"
	echo "# if you want to use another Slackware mirror and keep the dependency"
	echo "# information."
	echo "SOURCE=$repo/$arch/$slackdir-$version/:OFFICIAL"
	echo "SOURCE=$repo/$arch/$slackdir-$version/extra/:OFFICIAL"
	echo ""
	echo "# The Salix repository"
	echo "SOURCE=$repo/$arch/$version/:PREFERRED"
	echo ""
	echo "# Packages on a CD/DVD."
	echo "# SOURCE=file:///mnt/cdrom/:OFFICIAL"
	echo ""
	echo "# Home made packages."
	) > $SLAPTGETRC

	cat /tmp/reposetup.$$ >> $SLAPTGETRC
}

configslaptsrc(){
	(
	echo "BUILDDIR=$SLAPTSRCBUILDDIR"
	echo "PKGEXT=$SLAPTSRCPKGEXT"
	echo "SOURCE=$repo/slkbuild/$version/"
	echo "SOURCE=$repo/sbo/$version/"
	) > $SLAPTSRCRC
}

usage(){
echo "`eval_gettext 'USAGE:'` reposetup [[-m `eval_gettext 'mirror'`] [-n]]"
echo
echo "`eval_gettext 'OPTIONS:'`"
echo "    -m mirror,  `eval_gettext 'Specify a repository mirror manually'`"
echo "    -n,         `eval_gettext 'Do not update/ask for updating the package caches'`"
echo "    -h,         `eval_gettext 'This help message'`"
}

checkoptions(){
	while getopts ":hm:n" flag
	do
		# if switch is unknown or if asking for help
		if [ $flag = "?" ] || [ $flag = "h" ]; then
			usage
			exit 0
		fi
		if [ $flag = "m" ]; then
			# the repo URL has to be an http:// or ftp://
			# or even a file:// address for local files.
			# we're only doing very basic address checking
			# here
			if [[ "$OPTARG" == http://[[:alnum:]]* ]] \
				|| [[ "$OPTARG" == ftp://[[:alnum:]]* ]] \
				|| [[ "$OPTARG" == file://[[:alnum:]]* ]] ; then
				INTERACTIVE=0
				# remove trailing slashes
				repo="`echo \"$OPTARG\" | sed 's|/*$||g'`"
			else
				usage
				exit 1
			fi
		fi
		if [ $flag = "n" ]; then
			UPDATE=0
		fi
	done
	
	# we shift positions in $@ so that we discard all previous switches
	shift $((OPTIND-1))

	# There should be no more arguments
	if [ $# -gt 0 ]; then
		echo "`eval_gettext 'ERROR: Too many arguments'`" >&2
		usage
		exit 1
	fi
}

# This is the main thing!
init
checkdefaults
checkoptions $@

# Run interactive session
[ $INTERACTIVE -eq 1 ] && interactive

# Apply selected settings
configslaptget
configslaptsrc

# Update package caches
[ $UPDATE -eq 1 ] && updatecache

